# This config is stritcly for usage by the github action generate.yml
# The note that will be used as the index.html
# should be in obsidian_folder_path_str
# Use full path or relative path, but don't use ~/
obsidian_entrypoint_path_str: 'gardenbot.md'

##########################################################################
#                             HTML OUTPUT                                #
##########################################################################

# Will be inputted into the Html template as page title
# Not used anywhere else atm.
site_name: 'gardenbot/notes'

# Use when deploying to https://mydomain.com/html_prefix/ instead of https://mydomain.com/
# use '/html_prefix' (prepend slash, no slash at the end)
html_url_prefix: ''

file_exports:
  - encoding: binary
    src: resources/includes/favicon.ico
    dst: favicon.ico
  - src: resources/includes/test.md
    dst: test.md
# file_exports:
#   - encoding: binary
#     src: /home/dorus/Downloads/favicon.ico
#     dst: favicon.ico
#   - src: Resources/Includes/test.md
#     dst: test.md

navbar_links:
  - name: Home
    link: index.html
  - name: Wiring
    link: systems/wire-system/wire-system.html
  - name: GNSS RTK
    link: systems/localization-sysytem/gnss-rtk/usb-gnss-setup.html
  - name: Drive Motors
    link: systems/drive-system/drive-roboclaw-setup.html
  - name: Power System
    link: systems/power-system/power-system.html
  - name: Computer System
    link: systems/computer-system/computer-rpi.html

toggles:
  # Opt-in/-out of Obsidian->Md conversion, set to False when using proper markdown as input
  compile_md: True

  # Opt-in/-out of Md->Html conversion, set to False when only wanting to get proper markdown from Obsidian
  compile_html: True

  # If this is false only the entrypoint and all its links (recursively) are processed
  # if true all the notes will be processed
  process_all: False

  img_alt_text_use_figure: True

  slugify_html_links: True

  # Can be overwritten ad-hoc by using "obsidianhtml -i config.yml -v" (the -v option)
  verbose_printout: False
  debug_filetree_keys: False

  # This option should be False for Obsidian->Md, but can be True when compile_md == False
  # Setting it to True will cause an error when two files with the same file name are found anywhere in the input folder
  allow_duplicate_filenames_in_root: True

  # Sometimes linked images that should be local (based on the path) cannot be found.
  # Toggle this to False to disable warnings if that happens.
  warn_on_skipped_image: False

  # This will skip emptying output folders, if you want to implement this yourself
  no_clean: True

  # Whether the markdown interpreter assumes relative path when no / at the beginning of a link
  relative_path_md: True
  relative_path_html: False

  # Whether external http anchor links should have a target of "_blank"
  external_blank: False

  # Will preserve inline tags. This will give polluted markdown output
  preserve_inline_tags: True
  
  features:
    styling: 
      layout: documentation # documentation, tabs, no_tabs, minimal
      max_note_width: 70rem # not supported for layout: tabs
      header_template: full               # <full, minimal> currently only supported for documentation layout
      accent_color: '65, 76, 253'
      loading_bg_color: '22, 22, 22'

    # Show backlinks at the bottom of each note
    backlinks:
      enabled: True

    breadcrumbs:
      enabled: True

    theme_picker:
      enabled: True
      styling:
        show_icon: True

    graph:
      enabled: True           # Include code to build the graph view per page (default: True)
      templates:
        - id: 2d
          name: 2d
          path: builtin<2d>
        - id: 3d
          name: 3d
          path: builtin<3d>
      show_inclusions_in_graph: False
        # - id: custom
        #   name: custom
        #   path: ../obsidian-html.github.io/__src/custom_grapher.js
    search:
      enabled: True

    embedded_search:
      enabled: False

    dataview:
      enabled: False
      folder: 'obs.html/export' # relative to the vault being processed. this folder should always be in the vault

    folder_notes:
      enabled: True
      placement: 'inside folder'   # 'inside folder' , 'outside folder' 
      naming: 'folder name'

    create_index_from_dir_structure:
      enabled: True
      verbose: False
      rel_output_path: 'dirtree.html'
      styling: 
        show_icon: True
      exclude_subfolders:
        - ".git"
        - "__src"
        - "md"
        - "obs.html"
        - "resources"
        - "**/snippets"
      exclude_files:
        - ".gitignore"
        - "favicon.ico"
        - "not_created.html"
      homepage_label: "Home"

    table_of_contents:
      add_toc_when_missing: True          # add "[TOC]" (Table of Contents) when missing

    side_pane:             # only valid for documentation layout
      left_pane:
        enabled: True
        contents: dir_tree #tag_tree #html_page       # <toc, tag_tree, dir_tree> relevant features should be enabled and configured see docs
        width: 'max-content'
        content_args:
          rel_path: 'index.html'
          div_selector: '.container' # . for class, # for id
          #strip_tags:
          #  - 'babayaga'
          #  - 'bla'
          #  - 'randomothertag'
          
      right_pane:
        enabled: True
        contents: toc # <toc, tag_tree, dir_tree> relevant features should be enabled and configured see docs